// Code generated by terminal-protocol-gen. DO NOT EDIT.

package terminalcore

const (
	CodeTargetNotFound    = "TARGET_NOT_FOUND"
	CodeTargetNotRunning  = "TARGET_NOT_RUNNING"
	CodeLimitExceeded     = "LIMIT_EXCEEDED"
	CodeProtocolError     = "PROTOCOL_ERROR"
	CodeShellNotFound     = "SHELL_NOT_FOUND"
	CodeSlowProducer      = "SLOW_PRODUCER"
	CodeSlowConsumer      = "SLOW_CONSUMER"
	CodeSessionLost       = "SESSION_LOST"
	CodeInternal          = "INTERNAL"
	CodeServerDraining    = "SERVER_DRAINING"
	CodeSandboxTransition = "SANDBOX_TRANSITION"
)

const (
	CloseUserClosed        = "USER_CLOSED"
	CloseIdleTimeout       = "IDLE_TIMEOUT"
	CloseMaxLifetime       = "MAX_LIFETIME"
	CloseSandboxTransition = "SANDBOX_TRANSITION"
	CloseRuntimeExited     = "RUNTIME_EXITED"
	CloseSessionLost       = "SESSION_LOST"
	CloseProtocolError     = "PROTOCOL_ERROR"
	CloseServerDraining    = "SERVER_DRAINING"
	CloseSlowProducer      = "SLOW_PRODUCER"
	CloseSlowConsumer      = "SLOW_CONSUMER"
	CloseInternal          = "INTERNAL"
)

var terminalCloseReasons = map[string]struct{}{
	"USER_CLOSED":        {},
	"IDLE_TIMEOUT":       {},
	"MAX_LIFETIME":       {},
	"SANDBOX_TRANSITION": {},
	"RUNTIME_EXITED":     {},
	"SESSION_LOST":       {},
	"PROTOCOL_ERROR":     {},
	"SERVER_DRAINING":    {},
	"SLOW_PRODUCER":      {},
	"SLOW_CONSUMER":      {},
	"INTERNAL":           {},
}
