{{- if and .Values.cubeNode.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cube.nodeServiceAccountName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    app.kubernetes.io/component: cube-node
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- if and (eq (include "cube.proxyEnabled" .) "true") (dig "create" false (default dict .Values.cubeProxy.serviceAccount)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cube.proxyServiceAccountName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    app.kubernetes.io/component: cube-proxy
  {{- with (default dict .Values.cubeProxy.serviceAccount).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.controlPlane.enabled .Values.controlPlane.master.enabled (dig "create" false (default dict ((.Values.controlPlane).master).serviceAccount)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cube.masterServiceAccountName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
  {{- with (default dict ((.Values.controlPlane).master).serviceAccount).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
