apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eviction-webhook-tls
  namespace: cube-system
spec:
  secretName: eviction-webhook-tls
  dnsNames:
  - eviction-webhook.cube-system.svc
  - eviction-webhook.cube-system.svc.cluster.local
  issuerRef:
    name: cube-ca-issuer
    kind: ClusterIssuer
