# Copyright (c) 2026 Tencent Inc.
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
import shlex
from pathlib import Path

from dotenv import load_dotenv
from e2b_code_interpreter import Sandbox
from rich.console import Console


console = Console()


def load_local_dotenv() -> None:
    for path in (Path(__file__).with_name(".env"), Path.cwd() / ".env"):
        if path.is_file():
            load_dotenv(dotenv_path=path, override=False)
            return


def require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value


def sandbox_env() -> dict[str, str]:
    env = {
        "OPENCODE_DISABLE_AUTOUPDATE": "true",
    }
    for name in (
        "OPENAI_API_KEY",
        "ANTHROPIC_API_KEY",
        "OPENCODE_MODEL",
        "OPENCODE_CONFIG",
        "OPENCODE_CONFIG_CONTENT",
        "OPENCODE_CONFIG_DIR",
        "OPENCODE_SERVER_PASSWORD",
    ):
        value = os.environ.get(name)
        if value:
            env[name] = value
    return env


def seed_project(sandbox: Sandbox) -> None:
    sandbox.files.write(
        "/workspace/README.md",
        "# CubeSandbox OpenCode Demo\n\nThis project is generated by the OpenCode integration example.\n",
    )
    sandbox.files.write(
        "/workspace/app.py",
        "def hello(name: str) -> str:\n    return f'hello {name}'\n\nprint(hello('cube'))\n",
    )


def write_env_file(sandbox: Sandbox, env: dict[str, str]) -> str:
    path = "/tmp/opencode-env.sh"
    lines = [f"export {name}={shlex.quote(value)}" for name, value in env.items()]
    sandbox.files.write(path, "\n".join(lines) + "\n")
    return path


def run_command(sandbox: Sandbox, command: str, env_file: str) -> None:
    wrapped_command = f"set -a && . {env_file} && set +a && {command}"
    console.print(f"[bold cyan]$ {command}[/bold cyan]")
    result = sandbox.commands.run(
        wrapped_command,
        cwd="/workspace",
        timeout=900,
    )
    if result.stdout:
        console.print(result.stdout)
    if result.stderr:
        console.print(result.stderr, style="yellow")
    if getattr(result, "exit_code", 0) not in (0, None):
        raise SystemExit(f"Command failed with exit code {result.exit_code}")


def main() -> None:
    load_local_dotenv()

    parser = argparse.ArgumentParser(description="Run OpenCode inside Cube Sandbox.")
    parser.add_argument("--template", default=os.environ.get("CUBE_TEMPLATE_ID"))
    parser.add_argument("--prompt", default="Inspect this project and explain what it does.")
    parser.add_argument("--model", default=os.environ.get("OPENCODE_MODEL"))
    parser.add_argument("--snapshot", action="store_true", help="Create a snapshot after the run.")
    parser.add_argument("--network", choices=["default", "no-internet"], default="default")
    args = parser.parse_args()

    if not args.template:
        require_env("CUBE_TEMPLATE_ID")

    create_kwargs = {"template": args.template or os.environ["CUBE_TEMPLATE_ID"], "timeout": 900}
    if args.network == "no-internet":
        create_kwargs["allow_internet_access"] = False

    with Sandbox.create(**create_kwargs) as sandbox:
        console.print(f"[green]sandbox[/green] {sandbox.sandbox_id}")
        seed_project(sandbox)

        env_file = write_env_file(sandbox, sandbox_env())
        model_flag = f" --model {args.model}" if args.model else ""
        command = f"opencode run{model_flag} --auto {shlex.quote(args.prompt)}"
        run_command(sandbox, "opencode --version", env_file)
        run_command(sandbox, command, env_file)

        if args.snapshot:
            snapshot = sandbox.pause()
            console.print(f"[green]snapshot[/green] {snapshot.snapshot_id}")
            console.print("Use it as --template <snapshot-id> to resume the filesystem state.")


if __name__ == "__main__":
    main()
