// Code generated by terminal-protocol-gen. DO NOT EDIT.

package terminal

const (
	Subprotocol = "cube-terminal.v1"
	GrantPrefix = "cube-grant."

	ChannelStdin  byte = 0x00
	ChannelStdout byte = 0x01
	ChannelStderr byte = 0x02
	ChannelStatus byte = 0x03
	ChannelResize byte = 0x04

	MaxTerminalPayloadBytes = 65536
	maxStatusBytes          = 4096
	minTerminalDimension    = 1
	maxTerminalDimension    = 1000
)

var terminalErrorCodes = map[string]struct{}{
	"TARGET_NOT_FOUND":   {},
	"TARGET_NOT_RUNNING": {},
	"LIMIT_EXCEEDED":     {},
	"PROTOCOL_ERROR":     {},
	"SHELL_NOT_FOUND":    {},
	"SLOW_PRODUCER":      {},
	"SLOW_CONSUMER":      {},
	"SESSION_LOST":       {},
	"INTERNAL":           {},
	"SERVER_DRAINING":    {},
	"SANDBOX_TRANSITION": {},
}

var terminalCloseReasons = map[string]struct{}{
	"USER_CLOSED":        {},
	"IDLE_TIMEOUT":       {},
	"MAX_LIFETIME":       {},
	"SANDBOX_TRANSITION": {},
	"RUNTIME_EXITED":     {},
	"SESSION_LOST":       {},
	"PROTOCOL_ERROR":     {},
	"SERVER_DRAINING":    {},
	"SLOW_PRODUCER":      {},
	"SLOW_CONSUMER":      {},
	"INTERNAL":           {},
}
