FROM tencentos/tencentos4-minimal:latest

WORKDIR /work

RUN yum install -y \
    util-linux \
    busybox \
    gawk \
    gcc \
    util-linux \
    which \
    vim \
    sudo \
    lsof

CMD ["bash"]
